id = "rust-snippets-ultimate-etd"
name = "Zed Rust Snippets Ultimate Edition"
version = "0.0.1"
schema_version = 1
authors = ["Tim Lauridsen <tla@rasmil.dk>"]
description = "Rust snippets for the Zed IDE. A collection of Rust snippets to improve your development speed."
repository = "https://github.com/timlau/zed-rust-snippets"
snippets = "./snippets/rust.json"
